In [4]:
import numpy as np
import pandas as pd

In [15]:
a = 50
b = 15
a, b = b, a%b
print(a)
print(type(a))

15
<class 'int'>


In [16]:
matrix = [[j for j in range(5)] for i in range(3)]

print(matrix)

[[0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4]]


In [17]:
for i in range(3):           
    for j in range(5):      
        matrix[i][j] = j

print(matrix)

[[0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4]]


In [1]:
a=[i for i in range(5)] # a에 [0 1 2 3 4]를 할당
b=[a for j in range(3)] # b에 a를 3번할당
print(b)

[[0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4]]


In [5]:
matrix = [[0,1,2,3], [4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]]

a, b = np.split(matrix,[3],axis=0)
print(a)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]]


In [11]:
n,r=5,3
if n<r:
  result=0
else:
  result = 1
  for i in range(0,r):
   result *= (n-i)
  print(f"The permutation P(5,3) is: {result}")

The permutation P(5,3) is: 60


In [5]:
arr_zeros = np.zeros((2))
print(arr_zeros)

[0. 0.]


In [7]:
arr_ones = np.ones((3), dtype=int)
print(arr_ones)

[1 1 1]


In [10]:
# 1차원 배열을 2차원 배열로 변경
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr)
arr_reshaped = arr.reshape((2, 3))
print(arr_reshaped)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [11]:
# 0부터 10까지 2 간격으로 배열 생성
arr_range = np.arange(0, 11, 2)
print(arr_range)

# 0부터 1까지 5개의 값을 균일하게 생성
arr_linspace = np.linspace(0, 1, 5)
print(arr_linspace)

[ 0  2  4  6  8 10]
[0.   0.25 0.5  0.75 1.  ]


In [12]:
# 배열의 합, 평균, 표준편차 계산
arr = np.array([1, 2, 3, 4, 5])
print(np.sum(arr))
print(np.mean(arr))
print(np.std(arr))

15
3.0
1.4142135623730951


In [13]:
# 두 배열의 내적 계산
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(np.dot(arr1, arr2))

# 배열의 전치 계산
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.transpose(arr))

32
[[1 4]
 [2 5]
 [3 6]]


In [2]:
str = "https://patents.google.com/patent/US20240220323A1/en"

In [8]:
%pip install bs4

  Using cached bs4-0.0.2-py2.py3-none-any.whl.metadata (411 bytes)
  Using cached beautifulsoup4-4.12.3-py3-none-any.whl.metadata (3.8 kB)
  Using cached soupsieve-2.6-py3-none-any.whl.metadata (4.6 kB)
Using cached bs4-0.0.2-py2.py3-none-any.whl (1.2 kB)
Using cached beautifulsoup4-4.12.3-py3-none-any.whl (147 kB)
Using cached soupsieve-2.6-py3-none-any.whl (36 kB)
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [9]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

# 네트워크 호출을 위한 빈 리스트 생성
data = []

# 특허의 인용 문헌을 수집하는 함수 생성
def extract_citations(url):
    # URL에서 target patent 추출
    target_patent = url.split("/")[4]

    # 페이지 요청
    response = requests.get(url)
    soup = BeautifulSoup(response.text, 'html.parser')

    # 인용된 특허 수집 (backward_references)
    backward_references = soup.find_all('tr', itemprop='backwardReferences')
    backward_citations = [ref.find('span', itemprop='publicationNumber').text for ref in backward_references]

    # 인용한 특허 수집 (forward_references)
    forward_references = soup.find_all('tr', itemprop='forwardReferences')
    forward_citations = [ref.find('span', itemprop='publicationNumber').text for ref in forward_references]

    # 인용된 특허 -> 대상 특허가 source
    for citation in backward_citations:
        data.append({'source': target_patent, 'target': citation})

    # 인용한 특허 -> 대상 특허가 target
    for cited in forward_citations:
        data.append({'source': cited, 'target': target_patent})

# [result link]에서 URL 호출 및 데이터 수집
#for url in patent_df['result link']:
extract_citations(str)

# 수집된 데이터를 DataFrame 생성
citation_df = pd.DataFrame(data)

# 결과 출력
citation_df.shape


(2, 2)

In [10]:
citation_df

source           target
0  US20230236833A1  US20240220323A1
1     US12124847B2  US20240220323A1