In [3]:
import numpy as np
import pandas as pd

In [15]:
a = 50
b = 15
a, b = b, a%b
print(a)
print(type(a))

15
<class 'int'>


In [16]:
matrix = [[j for j in range(5)] for i in range(3)]

print(matrix)

[[0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4]]


In [17]:
for i in range(3):           
    for j in range(5):      
        matrix[i][j] = j

print(matrix)

[[0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4]]


In [1]:
a=[i for i in range(5)] # a에 [0 1 2 3 4]를 할당
b=[a for j in range(3)] # b에 a를 3번할당
print(b)

[[0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4]]


In [5]:
matrix = [[0,1,2,3], [4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]]

a, b = np.split(matrix,[3],axis=0)
print(a)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]]


In [11]:
n,r=5,3
if n<r:
  result=0
else:
  result = 1
  for i in range(0,r):
   result *= (n-i)
  print(f"The permutation P(5,3) is: {result}")

The permutation P(5,3) is: 60


In [16]:
되냐 = "ㅇㅇ?"
된다고 = "ㅇㅇ?!"
print(되냐, 된다고) 

ㅇㅇ? ㅇㅇ?!


In [17]:
def 되나():
    print(된다고)
되나()

ㅇㅇ?!
