In [4]:
import numpy as np
import pandas as pd

In [15]:
a = 50
b = 15
a, b = b, a%b
print(a)
print(type(a))

15
<class 'int'>


In [16]:
matrix = [[j for j in range(5)] for i in range(3)]

print(matrix)

[[0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4]]


In [17]:
for i in range(3):           
    for j in range(5):      
        matrix[i][j] = j

print(matrix)

[[0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4]]


In [1]:
a=[i for i in range(5)] # a에 [0 1 2 3 4]를 할당
b=[a for j in range(3)] # b에 a를 3번할당
print(b)

[[0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4]]


In [5]:
matrix = [[0,1,2,3], [4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]]

a, b = np.split(matrix,[3],axis=0)
print(a)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]]


In [11]:
n,r=5,3
if n<r:
  result=0
else:
  result = 1
  for i in range(0,r):
   result *= (n-i)
  print(f"The permutation P(5,3) is: {result}")

The permutation P(5,3) is: 60


In [5]:
arr_zeros = np.zeros((2))
print(arr_zeros)

[0. 0.]


In [7]:
arr_ones = np.ones((3), dtype=int)
print(arr_ones)

[1 1 1]


In [10]:
# 1차원 배열을 2차원 배열로 변경
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr)
arr_reshaped = arr.reshape((2, 3))
print(arr_reshaped)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [11]:
# 0부터 10까지 2 간격으로 배열 생성
arr_range = np.arange(0, 11, 2)
print(arr_range)

# 0부터 1까지 5개의 값을 균일하게 생성
arr_linspace = np.linspace(0, 1, 5)
print(arr_linspace)

[ 0  2  4  6  8 10]
[0.   0.25 0.5  0.75 1.  ]


In [12]:
# 배열의 합, 평균, 표준편차 계산
arr = np.array([1, 2, 3, 4, 5])
print(np.sum(arr))
print(np.mean(arr))
print(np.std(arr))

15
3.0
1.4142135623730951


In [13]:
# 두 배열의 내적 계산
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(np.dot(arr1, arr2))

# 배열의 전치 계산
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.transpose(arr))

32
[[1 4]
 [2 5]
 [3 6]]
